"""Cross-check our reproduced OriginalModel cost/lower-bound against the
per-instance numbers Shin et al. (2026) publish in their own paper (Table A.7
for the Lee benchmark, Table A.8 for the extremely-large-scale benchmark).

This is a stronger validity check than internal self-consistency (e.g.
ZeroShot(C=1) == OriginalModel): it verifies our independent re-implementation
reproduces the ORIGINAL AUTHORS' OWN published numbers, not just numbers
generated by our own pipeline.

Reference tables were extracted once from the published PDF
(1-s2.0-S0968090X25005005-main.pdf, Appendix, Tables A.7/A.8) into
benchmarks/published_tableA7.csv / published_tableA8.csv -- see
docs/superpowers/plans/2026-07-11-master-plan.md Phase 0.3.

Usage: python -m analysis.compare_published
"""
import pandas as pd
import numpy as np


def compare(results_csv, published_csv, label):
    ours = pd.read_csv(results_csv)
    ours = ours[ours['method'] == 'OriginalModel'][['instance', 'cost', 'lb']].copy()
    ours['problem'] = ours['instance'].str.replace('.txt', '', regex=False)

    pub = pd.read_csv(published_csv)

    merged = pub.merge(ours, on='problem', how='inner')
    print(f'\n=== {label}: {len(merged)}/{len(pub)} instances matched ===')
    if len(merged) == 0:
        print('  NO MATCHES -- check instance-name format between the two sources')
        return

    merged['lb_diff_pct'] = (merged['lb'] - merged['lb_published']).abs() / merged['lb_published'] * 100
    merged['cost_diff_pct'] = (merged['cost'] - merged['ours_published']).abs() / merged['ours_published'] * 100

    print(f'  LB   diff: max={merged.lb_diff_pct.max():.4f}%  mean={merged.lb_diff_pct.mean():.4f}%')
    print(f'  Cost diff: max={merged.cost_diff_pct.max():.4f}%  mean={merged.cost_diff_pct.mean():.4f}%')

    worst = merged.nlargest(5, 'cost_diff_pct')[['problem', 'lb', 'lb_published', 'cost', 'ours_published', 'cost_diff_pct']]
    if merged.cost_diff_pct.max() > 0.01:
        print('  Worst 5 by cost diff:')
        print(worst.to_string(index=False))
    else:
        print('  All matched instances reproduce published cost within rounding error.')
    return merged


if __name__ == '__main__':
    m7 = compare('results/single_crane_lee.csv', 'benchmarks/published_tableA7.csv',
                  'Lee benchmark (Table A.7)')
    m8 = compare('results/single_crane_shin.csv', 'benchmarks/published_tableA8.csv',
                  'Extremely-large-scale benchmark (Table A.8)')
